# Generated by Django 6.0.5 on 2026-05-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apiratelimit',
            index=models.Index(fields=['identifier'], name='payments_ap_identif_cf4d04_idx'),
        ),
        migrations.AddIndex(
            model_name='apiratelimit',
            index=models.Index(fields=['endpoint'], name='payments_ap_endpoin_b5d290_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['idempotency_key'], name='payments_id_idempot_104db4_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['state'], name='payments_id_state_dce79b_idx'),
        ),
    ]
