# Generated by Django 6.0.5 on 2026-05-10 16:44

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_apiratelimit_payments_ap_identif_cf4d04_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='request_body',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='response_body',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
